version: '3.7'

services:
  db:
    image: postgres:16.0-alpine
    restart: always
    volumes:
      - volume-bun_starter-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data

  api:
    image: kilann31/bun_image:test
    restart: always

    depends_on:
      - db
    ports:
        - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/app
    env_file:
      - .env
    command: ["bun", "dev"]

volumes:
  volume-bun_starter-db:
    name: ${DOMAIN_NAME}-bun_starter-volume-db